import type {
  Contact,
  EventDirty,
  EventDong,
  EventError,
  EventFriendship,
  EventHeartbeat,
  EventLogin,
  EventLogout,
  EventMessage,
  EventReady,
  EventReset,
  EventRoomInvite,
  EventRoomJoin,
  EventRoomLeave,
  EventRoomTopic,
  EventScan,
  EventTag,
  Friendship,
  FriendshipConfirm,
  FriendshipReceive,
  FriendshipVerify,
  Location,
  Message,
  MessageBase,
  MessageRoom,
  MessageTo,
  MiniProgram,
  RoomInvitation,
  RoomMember,
  Room,
  UrlLink,
  Post,
  PostClient,
  PostServer,
  Channel,
  Sayable,
  EventPost,
  Tag,
  TagGroup,
} from '@juzi/wechaty-puppet/payloads'

import {
  sayable,
  isPostServer,
  isPostClient,
} from '@juzi/wechaty-puppet/payloads'

export type {
  Contact as ContactPayload,
  EventDirty as EventDirtyPayload,
  EventDong as EventDongPayload,
  EventError as EventErrorPayload,
  EventFriendship as EventFriendshipPayload,
  EventHeartbeat as EventHeartbeatPayload,
  EventLogin as EventLoginPayload,
  EventLogout as EventLogoutPayload,
  EventMessage as EventMessagePayload,
  EventPost as EventPostPayload,
  EventReady as EventReadyPayload,
  EventReset as EventResetPayload,
  EventRoomInvite as EventRoomInvitePayload,
  EventRoomJoin as EventRoomJoinPayload,
  EventRoomLeave as EventRoomLeavePayload,
  EventRoomTopic as EventRoomTopicPayload,
  EventScan as EventScanPayload,
  EventTag as EventTagPayload,
  Friendship as FriendshipPayload,
  FriendshipConfirm as FriendshipPayloadConfirm,
  FriendshipReceive as FriendshipPayloadReceive,
  FriendshipVerify as FriendshipPayloadVerify,
  Location as LocationPayload,
  Message as MessagePayload,
  MessageBase as MessagePayloadBase,
  MessageRoom as MessagePayloadRoom,
  MessageTo as MessagePayloadTo,
  MiniProgram as MiniProgramPayload,
  Post as PostPayload,
  PostClient as PostPayloadClient,
  PostServer as PostPayloadServer,
  RoomInvitation as RoomInvitationPayload,
  RoomMember as RoomMemberPayload,
  Room as RoomPayload,
  Channel as ChannelPayload,
  Sayable as SayablePayload,
  Tap as TapPayload,
  UrlLink as UrlLinkPayload,
  Tag as TagPayload,
  TagGroup as TagGroupPayload,
}

export {
  sayable as sayablePayloads,
  isPostServer as isPostPayloadServer,
  isPostClient as isPostPayloadClient,
}